# Generated by Django 4.2.5 on 2023-10-13 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_item_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='image',
        ),
    ]
